### ISSUE TITLE
How to get predictions from the model?

### ISSUE THREAD

**Issue by metin-akyol** [allegro/allRank#55]
This question was asked before. Is there are a way to get the predictions of the model? What I mean by that is, for the test dataset, can we obtain the predicted ranks for each observation? So we can do our own evaluation of model performance?

Similar to the way the usual sklearn models would have a fit and a predict function?

This would be particularly useful to evaluate the model in a broader context and compare against other models that might not produce the same evaluation metrics.

**Comment by metin-akyol** [comment]
I have tried this, which I believe uses the forward function (the equivalent of predict- please correct me if I am wrong):

model(test_dl)

which produces this error:

TypeError: LTRModel.forward() missing 2 required positional arguments: 'mask' and 'indices'

I am not sure what mask and indices should be in this case.

**Comment by metin-akyol** [comment]
So my understanding is that I can use model.forward(test_dl, mask, indices) or model(test_dl, mask, indices) 
but it is not quite clear to me which values for mask and indices I should use. Inside of train_utils.py it appears that 3 functions that are wrapped utilize the similar score function, compute_metrics which contains metric_on_epoch which contains metric_on_batch which ultimately uses model.score.

Would it make sense to create the predictions at the end of the fit function? 

Or would it make more sense to do this outside in the main script. By accessing mask and indices in the model object?

Any help is highly appreciated.

**Comment by mhsyno** [comment]
Hello,

I believe the easiest way to access the predictions (given a trained model and a dataloader for the dataset you want predictions for) would be to slightly modify such a function from inference module: https://github.com/allegro/allRank/blob/2923985135c8afcdae6392e5b810b62da7851276/allrank/inference/inference_utils.py#L37 in the way to return scores (or masked scores), not items reranked according to scores as it works in current form. Please notice that with such a workaround there is no need for defining mask and indinces as these objects are created inside of the function.
As for the second question it feels natural to create the predictions in the main script since trained model is one of the arguments of `__rank_slates()` function.
Hope it helps.

Regards,
Mikołaj

**Comment by metin-akyol** [comment]
Thank you for your response. If I understand this function correctly, it returns the re-ranked dataset, which is the prediction that I am interested in. If I understand you correctly, you are suggesting to have it return scores of each observation, so I can then use those scores to assign my own rank by simply sorting based on scores. I will try both approaches. Thank you.

**Comment by metin-akyol** [comment]
Thank you again Mikołaj for your suggestion. Unfortunately, I have not been able to get this work yet. Is there any chance you (or anyone) might be able to share an example of how I can use say 10% of data from the validation datasetand get the predictions for those?

**Comment by metin-akyol** [comment]
So I was able to get this to work for those who are interested:

slates_X, slates_y = __rank_slates(val_dl, model)

val_dl is the dataloader object created in the way it is done win the main.py script.

Thanks Mikołaj for your help.
