### ISSUE TITLE
How to use your own dataset?

### ISSUE THREAD

**Issue by metin-akyol** [allegro/allRank#56]
Would it be possible to provide a brief explanation of the what the columns in the example dataset are (I am familiar with libsvm format from this description: https://catboost.ai/en/docs/concepts/input-data_libsvm but still don't fully understand)? The reason I am asking is, I would like to run the model on my own dataset but it isn't quite clear to me what the format of the data should be. I know that the paper has used MSLR-WEB30K but that one looked a bit different than this one.

Particularly, the dataset has:

1)  In the first column values from 0 to 4? Are the these the predicted ranks? 
2) The 2nd column has the qid with integer values from 0 to 99. I assume these are the query IDs.
3) The remaining columns appear to be features?  The integer indicating the feature name and the next one is the value (and so on)?

**Comment by mhsyno** [comment]
Hello,

as you mentioned, in our paper we used MSLR-WEB30K dataset which is perfectly described here: https://www.microsoft.com/en-us/research/project/mslr/
In [run_example.sh](https://github.com/allegro/allRank/blob/master/scripts/run_example.sh) data generated from [generate_dummy_data.py](https://github.com/allegro/allRank/blob/master/allrank/data/generate_dummy_data.py) are used. These data are of a standard libsvm format (but with query_id: https://github.com/allegro/allRank/blob/2923985135c8afcdae6392e5b810b62da7851276/allrank/data/dataset_loading.py#L130) which matches MLSR-WEB30K format (since the code is compatible with this dataset).
As for your questions:
1. In the first columns values from 0 to 4 are labels - these values depicts how relevant were responses in the context of a query (higher the value more relevant the response was). In the reranking task you want a list reranked by your model to be as close to sorting (descending) by these values as possible. Of course in your own dataset you can provide different number of unique values, even just binary (0, 1).
2. Correct, 2nd column depicts query id, which is used to determine groups of responses for each query (further used to calculate metrics).
3. That's right - remain columns are features in a format of sparse matrices.

**Comment by metin-akyol** [comment]
Great, thank you so much clarifying Mikolaj, I highly appreciate your help.
